#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>
#include <getopt.h>
#include "types.h"
#include "const.h"
#include "util.h"
#define _POSIX_C_Source 2

// TODO: implement
int serial_binsearch(int arr[], int l, int r, int x) {
	if(r>=1){
		int mid = l +(r-l)/2;
		if(arr[mid] == x) return mid;
		if(arr[mid]>x) return serial_binsearch(arr, l, mid-1, x);
		return serial_binsearch(arr, mid+1, r, x);
	}
    return 0;
}

// TODO: implement
int parallel_binsearch() {
    return 0;
}

int main(int argc, char** argv) {
    /* TODO: move this time measurement to right before the execution of each binsearch algorithms
     * in your experiment code. It now stands here just for demonstrating time measurement. */
    int experiments = 0 ;
    int t = 0;
    int position = 0;
    int c;
    clock_t cbegin = clock();

    printf("[binsearch] Starting up...\n");

    /* Get the number of CPU cores available */
    printf("[binsearch] Number of cores available: '%ld'\n",
           sysconf(_SC_NPROCESSORS_ONLN));

    /* TODO: parse arguments with getopt */
    
    while((c = getopt (argc, argv, "T:E:P:")) !=-1)
    	switch(c){
    		perror("[datagen] Bind error.\n");
			case 'T':
			t = atoi(optarg);
			if(t<3 || t>9){
				fprintf(stderr, "%s\n", "T must be betweeen 3 and 9");
				return 0;
			}
			
			case 'E':
			experiments = atoi(optarg);
			if(experiments<1){
				fprintf(stderr, "%s\n","Number of experiments must be greater or equal than 1" );
				return 0;
			}
			case 'P':
			position = atoi(optarg);
			if(position<0 || position>pow(10, t)-1){
				fprintf(stderr, "%s\n", "Position must be betweeen 0 and 10^T - 1");
			}
			

			
		

    	}
	printf("%d %d %d\n",t, experiments, position);


    

    /* TODO: start datagen here as a child process. */
    int dtgnid = fork();
    
    if(dtgnid >= 0){
    	printf("%s%d\n","Datagen PID: ", dtgnid );
    	char * name= "./datagen";
    	execvp(name, &name);
    }
    else if (dtgnid<0){
    	fprintf(stderr, "%s\n", "Can't create Datagen as ");
    }

    /* TODO: implement code for your experiments using data provided by datagen and your
     * serial and parallel versions of binsearch.
     * */

    /* TODO: connect to datagen and ask for the necessary data in each experiment round.
     * Create a Unix domain socket with DSOCKET_PATH (see const.h).
     * Talk to datagen using the messages specified in the assignment description document.
     * Read the values generated by datagen from the socket and use them to run your
     * experiments
     * */

    /* Probe time elapsed. */
    clock_t cend = clock();

    // Time elapsed in miliseconds.
    double time_elapsed = ((double) (cend - cbegin) / CLOCKS_PER_SEC) * 1000;

    printf("Time elapsed '%lf' [ms].\n", time_elapsed);

    exit(0);
}